"""
Unit tests for ml_platform_sdk.tasks.efs.

Tests use mocks/stubs to verify that the pod spec generated by build_efs_pod_template
and the efs_task decorator includes the expected EFS volume and volume mount.
"""

import pytest

from ml_platform_sdk.tasks.efs import (
    EFS_MOUNT_PATH,
    EFS_PVC_NAME,
    EFS_VOLUME_NAME,
    build_efs_pod_template,
    efs_task,
)


class TestConstants:
    def test_efs_mount_path(self):
        assert EFS_MOUNT_PATH == "/mnt/efs"

    def test_efs_pvc_name(self):
        assert EFS_PVC_NAME == "efs-claim"

    def test_efs_volume_name(self):
        assert EFS_VOLUME_NAME == "efs-storage"


class TestBuildEfsPodTemplate:
    def test_returns_pod_template(self):
        from flytekit import PodTemplate

        template = build_efs_pod_template()
        assert isinstance(template, PodTemplate)

    def test_pod_spec_has_one_volume(self):
        template = build_efs_pod_template()
        volumes = template.pod_spec.volumes
        assert len(volumes) == 1

    def test_volume_name(self):
        template = build_efs_pod_template()
        volume = template.pod_spec.volumes[0]
        assert volume.name == EFS_VOLUME_NAME

    def test_volume_uses_correct_pvc(self):
        template = build_efs_pod_template()
        pvc_source = template.pod_spec.volumes[0].persistent_volume_claim
        assert pvc_source is not None
        assert pvc_source.claim_name == EFS_PVC_NAME

    def test_volume_is_not_read_only_by_default(self):
        template = build_efs_pod_template()
        pvc_source = template.pod_spec.volumes[0].persistent_volume_claim
        # read_only defaults to False
        assert not pvc_source.read_only

    def test_container_has_volume_mount(self):
        template = build_efs_pod_template()
        containers = template.pod_spec.containers
        assert len(containers) == 1
        mounts = containers[0].volume_mounts
        assert len(mounts) == 1

    def test_volume_mount_path(self):
        template = build_efs_pod_template()
        mount = template.pod_spec.containers[0].volume_mounts[0]
        assert mount.mount_path == EFS_MOUNT_PATH

    def test_volume_mount_name_matches_volume(self):
        template = build_efs_pod_template()
        mount = template.pod_spec.containers[0].volume_mounts[0]
        assert mount.name == EFS_VOLUME_NAME

    # ------------------------------------------------------------------ #
    # Custom parameter tests
    # ------------------------------------------------------------------ #

    def test_custom_mount_path(self):
        template = build_efs_pod_template(mount_path="/data/shared")
        mount = template.pod_spec.containers[0].volume_mounts[0]
        assert mount.mount_path == "/data/shared"

    def test_custom_pvc_name(self):
        template = build_efs_pod_template(pvc_name="my-efs-pvc")
        pvc_source = template.pod_spec.volumes[0].persistent_volume_claim
        assert pvc_source.claim_name == "my-efs-pvc"

    def test_read_only_flag(self):
        template = build_efs_pod_template(read_only=True)
        pvc_source = template.pod_spec.volumes[0].persistent_volume_claim
        assert pvc_source.read_only is True
        mount = template.pod_spec.containers[0].volume_mounts[0]
        assert mount.read_only is True


class TestEfsTaskDecorator:
    """Smoke-test that efs_task produces a valid Flyte task object."""

    def test_efs_task_wraps_function(self):
        @efs_task()
        def sample(x: int) -> int:
            return x * 2

        # Flytekit wraps the function in a Task object; ensure it is callable
        assert callable(sample)

    def test_efs_task_preserves_name(self):
        @efs_task()
        def compute(x: int) -> int:
            return x + 1

        # The task name should reflect the original function name
        assert "compute" in compute.name

    def test_efs_task_pod_template_has_efs_mount(self):
        @efs_task()
        def process(x: str) -> str:
            return x

        template = process.pod_template
        assert template is not None
        volumes = template.pod_spec.volumes
        assert any(v.name == EFS_VOLUME_NAME for v in volumes)
        mounts = template.pod_spec.containers[0].volume_mounts
        assert any(m.mount_path == EFS_MOUNT_PATH for m in mounts)

    def test_efs_task_custom_mount_path(self):
        @efs_task(mount_path="/opt/efs")
        def read_data(path: str) -> str:
            return path

        template = read_data.pod_template
        mounts = template.pod_spec.containers[0].volume_mounts
        assert any(m.mount_path == "/opt/efs" for m in mounts)

    def test_efs_task_custom_pvc_name(self):
        @efs_task(pvc_name="custom-pvc")
        def write_data(x: str) -> None:
            pass

        template = write_data.pod_template
        volumes = template.pod_spec.volumes
        pvc_names = [v.persistent_volume_claim.claim_name for v in volumes if v.persistent_volume_claim]
        assert "custom-pvc" in pvc_names
